# Generated by Django 5.1.6 on 2025-02-16 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartBin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('cover', models.CharField(default='Closed', max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('fill_level', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='user', max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(default='Not Specified', max_length=20)),
                ('status', models.CharField(default='Inactive', max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('autonomy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('waste_type', models.CharField(max_length=20)),
                ('time_collected', models.DateTimeField(auto_now_add=True)),
                ('smartbin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.smartbin')),
                ('wastebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.wastebot')),
            ],
        ),
    ]
