# Generated by Django 5.1.6 on 2025-02-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('trash_id', models.AutoField(primary_key=True, serialize=False)),
                ('trash_type', models.CharField(max_length=20)),
                ('time_collected', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField()),
                ('confidence_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrashBot',
            fields=[
                ('trashbot_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('battery_level', models.IntegerField()),
                ('last_maintenance', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SmartBin',
            fields=[
                ('smartbin_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('fill_level', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('trash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.trash')),
            ],
        ),
        migrations.AddField(
            model_name='trash',
            name='trashbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trashbot'),
        ),
    ]
