# Generated by Django 5.1.6 on 2025-02-12 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartbin',
            name='trash',
        ),
        migrations.RemoveField(
            model_name='trash',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='trash',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='trashbot',
            name='battery_level',
        ),
        migrations.RemoveField(
            model_name='trashbot',
            name='last_maintenance',
        ),
        migrations.AddField(
            model_name='trash',
            name='smartbin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.smartbin'),
        ),
        migrations.AddField(
            model_name='trashbot',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('full', 'Full')], default='active', max_length=10),
        ),
    ]
