# Generated by Django 5.1.6 on 2025-02-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_admin_agent_remove_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
