# Generated by Django 5.1.6 on 2025-02-14 11:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_smartbin_trash_remove_trash_confidence_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trash',
            new_name='Waste',
        ),
        migrations.RenameModel(
            old_name='TrashBot',
            new_name='WasteBot',
        ),
        migrations.RenameField(
            model_name='waste',
            old_name='trashbot',
            new_name='wastebot',
        ),
    ]
