# Generated by Django 5.1.6 on 2025-02-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
