# Generated by Django 5.1.6 on 2025-04-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmartBin',
            new_name='WasteBin',
        ),
        migrations.RenameField(
            model_name='waste',
            old_name='smartbin',
            new_name='WasteBin',
        ),
    ]
