# Generated by Django 5.1.6 on 2025-04-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_smartbin_wastebin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastebin',
            old_name='status',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='wastebin',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='wastebin',
            name='fill_level',
        ),
        migrations.RemoveField(
            model_name='wastebin',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='wastebin',
            name='temperature',
        ),
    ]
