# Generated by Django 5.1.6 on 2025-02-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waste',
            old_name='trash_id',
            new_name='waste_id',
        ),
        migrations.RenameField(
            model_name='waste',
            old_name='trash_type',
            new_name='waste_type',
        ),
        migrations.RenameField(
            model_name='wastebot',
            old_name='trashbot_id',
            new_name='wastebot_id',
        ),
    ]
