# Generated by Django 5.1.6 on 2025-05-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_status_wastebin_type_remove_wastebin_cover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waste',
            old_name='WasteBin',
            new_name='wastebin',
        ),
    ]
