# Generated by Django 5.1.6 on 2025-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_trash_id_waste_waste_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartbin',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('full', 'Full')], default='active', max_length=20),
        ),
    ]
