# Generated by Django 5.1.6 on 2025-02-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_user_alter_smartbin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastebot',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
