# Generated by Django 5.1.6 on 2025-02-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartbin',
            old_name='smartbin_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='waste',
            old_name='waste_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wastebot',
            old_name='wastebot_id',
            new_name='id',
        ),
    ]
