# Generated by Django 5.1.6 on 2025-02-14 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_smartbin_id_smartbin_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastebot',
            name='user',
        ),
    ]
