# Generated by Django 5.1.6 on 2025-02-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_wastebot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastebot',
            name='autonomy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wastebot',
            name='model',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='fill_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wastebot',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wastebot',
            name='status',
            field=models.CharField(default='Inactive', max_length=20),
        ),
    ]
