# Generated by Django 5.1.6 on 2025-02-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_wastebot_autonomy_wastebot_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastebot',
            name='autonomy',
            field=models.IntegerField(),
        ),
    ]
