# Generated by Django 5.1.6 on 2025-02-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_wastebot_autonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastebot',
            name='model',
            field=models.CharField(default='Not Specified', max_length=20),
        ),
    ]
