# Generated by Django 5.1.6 on 2025-02-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_wastebot_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastebot',
            name='cover',
            field=models.CharField(default='Closed', max_length=20),
        ),
    ]
