# Generated by Django 5.1.6 on 2025-02-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_wastebot_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastebot',
            name='cover',
        ),
        migrations.AddField(
            model_name='smartbin',
            name='cover',
            field=models.CharField(default='Closed', max_length=20),
        ),
    ]
